### ISSUE TITLE
meta: things todo before recommending a switch from cmi

### ISSUE THREAD

**Issue by wjwwood** [catkin/catkin_tools#90]
This is a list of things we need to get done before we make the official switch to `catkin build` and move away from using `catkin_make_isolated`.
#### bugs
- [x] Installed libraries reference devel space (https://github.com/catkin/catkin_tools/issues/70)
  - [x] Related: https://github.com/catkin/catkin_tools/issues/69
- [x] catkin: should not fail if cmake is not available (https://github.com/catkin/catkin_tools/issues/61)
- [x] leaf_sources out of bounds error (https://github.com/catkin/catkin_tools/issues/45)
#### missing functionality or features
- [x] build: support for arch-specific library folders (https://github.com/catkin/catkin_tools/issues/154)
- [x] build: test for compatibility with DESTDIR (~~https://github.com/catkin/catkin_tools/issues/31~~) (closed by https://github.com/catkin/catkin_tools/pull/240)
- [ ] build: test for topological ordering with underlays (https://github.com/catkin/catkin_tools/issues/30)
- [ ] build: speed up setup.sh for non-merged devel spaces (https://github.com/catkin/catkin_tools/issues/28)
  - [x] This issue also applies to this in general: https://github.com/catkin/catkin_tools/issues/74
  - [x] Also this: https://github.com/catkin/catkin_tools/issues/23
- [x] Bash/Zsh completion (https://github.com/catkin/catkin_tools/issues/15)
- [x] Detect warnings like rosmake (https://github.com/catkin/catkin_tools/issues/1)
- [x] build: support invocation from within symlink folders (#91) (ros/catkin#638)

**Comment by dirk-thomas** [comment]
Since it has been announced on *ros-users* and likely more users will start using it / looking into it I think the still missing features compared to `catkin_make(_isolated)` should be listed clearly in the documentation.

**Comment by jbohren** [comment]
Yeah, I think that would be a helpful page to have. Dirk, do you have any time to start it?

**Comment by dirk-thomas** [comment]
I don't think I am aware enough about the progress of `catkin_tools` to know what is supported right now and what isn't. Basically because I am rarely using the took.

I also don't have the time to check if the tool actually supports the features e.g. listed at the top of this ticket, sorry. Others might know this out of their heads?
